### ISSUE TITLE
윈도우 동작

### ISSUE THREAD

**Issue by changwoo** [changwoo/ko-po-check#31]
파이썬 기능만 쓰니까 딱히 안 돌아갈 이유는 없는데 일단 path separator (/ vs \) 차이로 동작하지 않는다고 한다.

**Comment by darkcircle** [comment]
* Python 3.7.0에서 테스트 (2018.08.27) 해본 결과 path separator 문제는 아닙니다.
  https://github.com/changwoo/ko-po-check/blob/master/scripts/ko-po-check#L63
  위 코드에서 os.sep.join() 의 동작을 의심하였으나 이 문제로 오류가 나타나지 않음.
* 오히려 cp949 인코딩 문제로 동작 멈춤.
```
C:\Users\biocon\AppData\Local\Programs\Python\Python37\Scripts>python ko-po-check c:\Users\biocon\Documents\release-notes.gnome-3-30.help.ko.po
Traceback (most recent call last):
  File "ko-po-check", line 92, in <module>
    catalog = poparse.parse_file(fp)
  File "C:\Users\biocon\AppData\Local\Programs\Python\Python37\lib\site-packages\KPC\poparse.py", line 39, in parse_file
    (entry, lineno) = parse_entry(reader, lineno)
  File "C:\Users\biocon\AppData\Local\Programs\Python\Python37\lib\site-packages\KPC\poparse.py", line 87, in parse_entry
    line = file.readline()
UnicodeDecodeError: 'cp949' codec can't decode byte 0xed in position 798: illegal multibyte sequence
```
